# Generated by Django 5.0 on 2023-12-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_form_age_form_city_form_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
